
templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: simpleReport.jrxml
    attributes:
      mapDef1: !map
        maxDpi: 400
        width: 360
        height: 330
      mapDef2: !map
        maxDpi: 400
        width: 360
        height: 330                    
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: 
        mapDef1: map
      outputMapper:
        mapSubReport: mapSubReport1
        mapContext: mapContext1      
    - !createMap
      inputMapper: 
        mapDef2: map
      outputMapper:
        mapSubReport: mapSubReport2
        mapContext: mapContext2     
