
throwErrorOnExtraParameters: true

templates:
  A4 portrait: !template
    reportTemplate: simpleReport.jrxml
    attributes:
      id_linia: !integer {}
      description: !string {}
      map: !map
        maxDpi: 400
        width: 400
        height: 200
      datasource: !datasource
        attributes:
          linia_name: !string {}
          table: !table {}
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: map}
    - !createDataSource
      reportTemplate: table.jrxml
      reportKey: reportTemplate
      processors:
        - !prepareTable {}
    tableData: jrDataSource
